services:
  app:
    build: .
    container_name: test_energy_container
    working_dir: /code/src
    command: ["jupyter", "notebook", "--port=8888", "--no-browser", "--ip=0.0.0.0", "--allow-root"]
    volumes:
      - .:/code
    ports:
      - "8888:8888"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]

  autoresearch-train:
    build: .
    working_dir: /code/src
    volumes:
      - .:/code
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    entrypoint: ["python"]

volumes:
  stonkapp:
