from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

import torch

from aemo_notebook_utils import partition_dt_dataset_for_subset_training


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train the Decision Transformer on AEMO trajectory logs.",
    )
    parser.add_argument(
        "--dataset-path",
        type=Path,
        default=repo_root() / "data" / "aemo_dt" / "aemo_dt_dataset.parquet",
        help="Path to the AEMO DT parquet dataset generated by notebooks/aemo_simrun.ipynb.",
    )
    parser.add_argument(
        "--model-config",
        type=Path,
        default=repo_root() / "configs" / "aemo_decision_transformer_model_kwargs.json",
        help="Path to the AEMO DT model kwargs JSON.",
    )
    parser.add_argument(
        "--surface-preset",
        type=str,
        default="aemo_learning_baseline",
        help=(
            "DT training surface preset forwarded to src/pretrain_decision_transformer.py. "
            "Use aemo_learning_baseline for broader baseline training or aemo_proxy for cheap triage."
        ),
    )
    parser.add_argument(
        "--model-variant",
        type=str,
        default=None,
        help="Optional DT model variant forwarded to src/pretrain_decision_transformer.py.",
    )
    parser.add_argument(
        "--save-path",
        type=Path,
        default=repo_root() / "models" / "aemo" / "dt" / "aemo_dt_model.pt",
        help="Where to store the trained AEMO DT weights.",
    )
    parser.add_argument(
        "--checkpoint-path",
        type=Path,
        default=repo_root() / "models" / "aemo" / "dt" / "aemo_dt_checkpoint.pt",
        help="Optional checkpoint path for intermediate saves.",
    )
    parser.add_argument(
        "--loss-csv-path",
        type=Path,
        default=repo_root() / "models" / "aemo" / "dt" / "aemo_dt_loss_history.csv",
        help="Optional path to save AEMO DT loss history as CSV.",
    )
    parser.add_argument("--epochs", type=int, default=2)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--lr", type=float, default=2e-5)
    parser.add_argument(
        "--val-split",
        type=float,
        default=0.1,
        help="Fraction of samples reserved for validation.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--device",
        type=str,
        default=None,
        help="Device string understood by torch (e.g. cuda, cuda:0, cpu).",
    )
    parser.add_argument(
        "--amp-mode",
        choices=["auto", "on", "off"],
        default="off",
        help="Automatic mixed precision mode: auto (GPU only), on (force on CUDA), off (disable).",
    )
    parser.add_argument("--checkpoint-interval", type=int, default=1)
    parser.add_argument("--checkpoints-per-epoch", type=int, default=6)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--return-scale", type=float, default=1.0)
    parser.add_argument("--action-loss-weight", type=float, default=1.0)
    parser.add_argument("--state-loss-weight", type=float, default=0.01)
    parser.add_argument("--return-loss-weight", type=float, default=0.002)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument(
        "--no-persistent-workers",
        dest="persistent_workers",
        action="store_false",
        help="Disable persistent DataLoader workers.",
    )
    parser.set_defaults(persistent_workers=True)
    parser.add_argument("--prefetch-factor", type=int, default=2)
    parser.add_argument("--rope-enabled", action="store_true")
    parser.add_argument("--rope-max-position", type=int, default=None)
    parser.add_argument("--rope-base", type=float, default=None)
    parser.add_argument(
        "--train-in-subsets",
        action="store_true",
        help="Split the AEMO parquet into episode-based subset files and train across them sequentially.",
    )
    parser.add_argument(
        "--subset-episodes",
        type=int,
        default=None,
        help="Number of full episodes to include in each generated subset parquet when --train-in-subsets is enabled.",
    )
    parser.add_argument(
        "--subset-output-dir",
        type=Path,
        default=None,
        help="Directory where episode-based AEMO subset parquet files will be written.",
    )
    parser.add_argument(
        "--epochs-per-subset",
        type=int,
        default=None,
        help="Epoch count to use for each subset run. Defaults to --epochs when omitted.",
    )
    return parser.parse_args()


def build_training_command(
    *,
    root: Path,
    args: argparse.Namespace,
    dataset_path: Path,
    epochs: int,
    resume: bool,
    val_data_dir: Path | None = None,
    val_patterns: list[str] | None = None,
) -> list[str]:
    model_config_path = args.model_config.resolve()
    save_path = args.save_path.resolve()
    checkpoint_path = args.checkpoint_path.resolve()
    loss_csv_path = args.loss_csv_path.resolve()

    command = [
        sys.executable,
        str(root / "src" / "pretrain_decision_transformer.py"),
        "--surface-preset",
        args.surface_preset,
        "--data-dir",
        str(dataset_path.parent),
        "--patterns",
        dataset_path.stem,
        "--model-config",
        str(model_config_path),
        "--epochs",
        str(epochs),
        "--batch-size",
        str(args.batch_size),
        "--lr",
        str(args.lr),
        "--val-split",
        str(0.0 if val_data_dir is not None else args.val_split),
        "--seed",
        str(args.seed),
        "--save-path",
        str(save_path),
        "--checkpoint-path",
        str(checkpoint_path),
        "--loss-csv-path",
        str(loss_csv_path),
        "--amp-mode",
        args.amp_mode,
        "--return-scale",
        str(args.return_scale),
        "--action-loss-weight",
        str(args.action_loss_weight),
        "--state-loss-weight",
        str(args.state_loss_weight),
        "--return-loss-weight",
        str(args.return_loss_weight),
        "--weight-decay",
        str(args.weight_decay),
        "--num-workers",
        str(args.num_workers),
        "--prefetch-factor",
        str(args.prefetch_factor),
        "--checkpoint-interval",
        str(args.checkpoint_interval),
        "--checkpoints-per-epoch",
        str(args.checkpoints_per_epoch),
    ]

    if val_data_dir is not None:
        command.extend(["--val-data-dir", str(val_data_dir)])
        if val_patterns:
            command.append("--val-patterns")
            command.extend(val_patterns)
    if args.model_variant is not None:
        command.extend(["--model-variant", args.model_variant])

    if resume:
        command.append("--resume")
    if args.device is not None:
        command.extend(["--device", args.device])
    if not args.persistent_workers:
        command.append("--no-persistent-workers")
    if args.rope_enabled:
        command.append("--rope-enabled")
    if args.rope_max_position is not None:
        command.extend(["--rope-max-position", str(args.rope_max_position)])
    if args.rope_base is not None:
        command.extend(["--rope-base", str(args.rope_base)])
    return command


def build_training_commands(
    *,
    root: Path,
    args: argparse.Namespace,
    dataset_paths: list[Path],
    epochs_per_stage: int,
    initial_epoch_offset: int = 0,
    val_dataset_paths: list[Path] | None = None,
) -> list[list[str]]:
    commands: list[list[str]] = []
    val_data_dir: Path | None = None
    val_patterns: list[str] | None = None
    if val_dataset_paths:
        val_data_dir = val_dataset_paths[0].parent
        val_patterns = [path.stem for path in val_dataset_paths]
    for index, dataset_path in enumerate(dataset_paths):
        commands.append(
            build_training_command(
                root=root,
                args=args,
                dataset_path=dataset_path,
                epochs=initial_epoch_offset + (epochs_per_stage * (index + 1)),
                resume=bool(args.resume or index > 0),
                val_data_dir=val_data_dir,
                val_patterns=val_patterns,
            )
        )
    return commands


def get_checkpoint_epoch(checkpoint_path: Path) -> int:
    if not checkpoint_path.is_file():
        return 0
    checkpoint = torch.load(checkpoint_path, map_location="cpu")
    return int(checkpoint.get("epoch", 0))


def main() -> None:
    args = parse_args()
    root = repo_root()

    dataset_path = args.dataset_path.resolve()
    model_config_path = args.model_config.resolve()

    if not dataset_path.is_file():
        raise FileNotFoundError(f"AEMO dataset not found: {dataset_path}")
    if not model_config_path.is_file():
        raise FileNotFoundError(f"AEMO model config not found: {model_config_path}")

    dataset_paths = [dataset_path]
    val_dataset_paths: list[Path] | None = None
    epochs_per_stage = int(args.epochs)
    initial_epoch_offset = get_checkpoint_epoch(args.checkpoint_path.resolve()) if args.resume else 0

    if args.surface_preset == "aemo_learning_baseline":
        if not args.train_in_subsets:
            raise ValueError(
                "--surface-preset=aemo_learning_baseline requires --train-in-subsets so the wrapper can "
                "create explicit held-out validation subsets."
            )
        if args.subset_episodes is None:
            args.subset_episodes = 24

    if args.train_in_subsets:
        if args.subset_episodes is None:
            raise ValueError("--subset-episodes is required when --train-in-subsets is enabled.")
        subset_output_dir = args.subset_output_dir
        if subset_output_dir is None:
            subset_output_dir = dataset_path.parent / f"{dataset_path.stem}_subsets"
        subset_manifest = partition_dt_dataset_for_subset_training(
            dataset_path=dataset_path,
            output_dir=subset_output_dir,
            subset_episode_count=args.subset_episodes,
            val_split=args.val_split,
            seed=args.seed,
        )
        dataset_paths = [Path(entry["path"]) for entry in subset_manifest["train_subsets"]]
        val_dataset_paths = [Path(entry["path"]) for entry in subset_manifest["val_subsets"]]
        epochs_per_stage = int(args.epochs_per_subset or args.epochs)
        print(
            f"Partitioned {dataset_path.name} into {len(dataset_paths)} subset files "
            f"with up to {args.subset_episodes} episodes each."
        )
        print(f"Subset manifest: {subset_manifest['manifest_path']}")
        print(
            f"Global split: train episodes={subset_manifest['train_episode_count']}, "
            f"val episodes={subset_manifest['val_episode_count']}"
        )
    elif args.val_split < 0.0 or args.val_split > 1.0:
        raise ValueError("--val-split must be between 0.0 and 1.0.")

    commands = build_training_commands(
        root=root,
        args=args,
        dataset_paths=dataset_paths,
        epochs_per_stage=epochs_per_stage,
        initial_epoch_offset=initial_epoch_offset,
        val_dataset_paths=val_dataset_paths,
    )
    for subset_index, command in enumerate(commands, start=1):
        if len(commands) > 1:
            print(f"Launching subset {subset_index}/{len(commands)} via:")
        else:
            print("Launching AEMO Decision Transformer training via:")
        print(" ".join(command))
        subprocess.run(command, check=True)


if __name__ == "__main__":
    main()
