from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path


def repo_root() -> Path:
    return Path(__file__).resolve().parents[1]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Train the Decision Transformer on AEMO trajectory logs.",
    )
    parser.add_argument(
        "--dataset-path",
        type=Path,
        default=repo_root() / "data" / "aemo_dt" / "aemo_dt_dataset.parquet",
        help="Path to the AEMO DT parquet dataset generated by aemo_simrun.ipynb.",
    )
    parser.add_argument(
        "--model-config",
        type=Path,
        default=repo_root() / "configs" / "aemo_decision_transformer_model_kwargs.json",
        help="Path to the AEMO DT model kwargs JSON.",
    )
    parser.add_argument(
        "--save-path",
        type=Path,
        default=repo_root() / "models" / "aemo_dt_model.pt",
        help="Where to store the trained AEMO DT weights.",
    )
    parser.add_argument(
        "--checkpoint-path",
        type=Path,
        default=repo_root() / "models" / "aemo_dt_checkpoint.pt",
        help="Optional checkpoint path for intermediate saves.",
    )
    parser.add_argument(
        "--loss-csv-path",
        type=Path,
        default=repo_root() / "models" / "aemo_dt_loss_history.csv",
        help="Optional path to save AEMO DT loss history as CSV.",
    )
    parser.add_argument("--epochs", type=int, default=2)
    parser.add_argument("--batch-size", type=int, default=8)
    parser.add_argument("--lr", type=float, default=2e-5)
    parser.add_argument(
        "--val-split",
        type=float,
        default=0.1,
        help="Fraction of samples reserved for validation.",
    )
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument(
        "--device",
        type=str,
        default=None,
        help="Device string understood by torch (e.g. cuda, cuda:0, cpu).",
    )
    parser.add_argument(
        "--amp-mode",
        choices=["auto", "on", "off"],
        default="off",
        help="Automatic mixed precision mode: auto (GPU only), on (force on CUDA), off (disable).",
    )
    parser.add_argument("--checkpoint-interval", type=int, default=1)
    parser.add_argument("--checkpoints-per-epoch", type=int, default=6)
    parser.add_argument("--resume", action="store_true")
    parser.add_argument("--return-scale", type=float, default=1.0)
    parser.add_argument("--action-loss-weight", type=float, default=1.0)
    parser.add_argument("--state-loss-weight", type=float, default=0.01)
    parser.add_argument("--return-loss-weight", type=float, default=0.002)
    parser.add_argument("--weight-decay", type=float, default=1e-4)
    parser.add_argument("--num-workers", type=int, default=2)
    parser.add_argument(
        "--no-persistent-workers",
        dest="persistent_workers",
        action="store_false",
        help="Disable persistent DataLoader workers.",
    )
    parser.set_defaults(persistent_workers=True)
    parser.add_argument("--prefetch-factor", type=int, default=2)
    parser.add_argument("--rope-enabled", action="store_true")
    parser.add_argument("--rope-max-position", type=int, default=None)
    parser.add_argument("--rope-base", type=float, default=None)
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    root = repo_root()

    dataset_path = args.dataset_path.resolve()
    model_config_path = args.model_config.resolve()
    save_path = args.save_path.resolve()
    checkpoint_path = args.checkpoint_path.resolve()
    loss_csv_path = args.loss_csv_path.resolve()

    if not dataset_path.is_file():
        raise FileNotFoundError(f"AEMO dataset not found: {dataset_path}")
    if not model_config_path.is_file():
        raise FileNotFoundError(f"AEMO model config not found: {model_config_path}")

    script_path = root / "src" / "pretrain_decision_transformer.py"
    command = [
        sys.executable,
        str(script_path),
        "--data-dir",
        str(dataset_path.parent),
        "--patterns",
        dataset_path.stem,
        "--model-config",
        str(model_config_path),
        "--epochs",
        str(args.epochs),
        "--batch-size",
        str(args.batch_size),
        "--lr",
        str(args.lr),
        "--val-split",
        str(args.val_split),
        "--seed",
        str(args.seed),
        "--save-path",
        str(save_path),
        "--checkpoint-path",
        str(checkpoint_path),
        "--loss-csv-path",
        str(loss_csv_path),
        "--amp-mode",
        args.amp_mode,
        "--return-scale",
        str(args.return_scale),
        "--action-loss-weight",
        str(args.action_loss_weight),
        "--state-loss-weight",
        str(args.state_loss_weight),
        "--return-loss-weight",
        str(args.return_loss_weight),
        "--weight-decay",
        str(args.weight_decay),
        "--num-workers",
        str(args.num_workers),
        "--prefetch-factor",
        str(args.prefetch_factor),
        "--checkpoint-interval",
        str(args.checkpoint_interval),
        "--checkpoints-per-epoch",
        str(args.checkpoints_per_epoch),
    ]

    if args.resume:
        command.append("--resume")
    if args.device is not None:
        command.extend(["--device", args.device])
    if not args.persistent_workers:
        command.append("--no-persistent-workers")
    if args.rope_enabled:
        command.append("--rope-enabled")
    if args.rope_max_position is not None:
        command.extend(["--rope-max-position", str(args.rope_max_position)])
    if args.rope_base is not None:
        command.extend(["--rope-base", str(args.rope_base)])

    print("Launching AEMO Decision Transformer training via:")
    print(" ".join(command))
    subprocess.run(command, check=True)


if __name__ == "__main__":
    main()